"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _admin_login_form from './admin-login-form.bones.json'
import _owner_login_form from './owner-login-form.bones.json'

registerBones({
  "admin-login-form": _admin_login_form,
  "owner-login-form": _owner_login_form,
})
